rmcgirr83_stopforumspam_core_reporttosfs:
    path: /reporttosfs/{username}/{userip}/{useremail}/{forumid}/{topicid}/{postid}/{posterid}
    defaults: { _controller: rmcgirr83.stopforumspam.core.reporttosfs:reporttosfs }
