rmcgirr83_stopforumspam_core_reporttosfs:
    path: /reporttosfs/{username}/{userip}/{useremail}
    defaults: { _controller: rmcgirr83.stopforumspam.core.reporttosfs:reporttosfs }
    requirements:
        username: '\s+'
        userip: '\s+'
        useremail: '\s+'
