services:
    rmcgirr83.stopforumspam.mainlistener:
        class: rmcgirr83\stopforumspam\event\main_listener
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@user'
            - '@dbal.conn'
            - '@controller.helper'
            - '@log'
            - '@request'
            - '@template'
            - '@rmcgirr83.stopforumspam.core.sfsgroups'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@?rmcgirr83.contactadmin.main.controller'
        tags:
            - { name: event.listener }
    rmcgirr83.stopforumspam.core.reporttosfs:
        class: rmcgirr83\stopforumspam\core\reporttosfs
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@log'
            - '@request'
            - '@user'
            - '@rmcgirr83.stopforumspam.core.sfsgroups'
    rmcgirr83.stopforumspam.core.sfsgroups:
        class: rmcgirr83\stopforumspam\core\sfsgroups
        arguments:
            - '@auth'
            - '@cache'
