services:
    stopforumspam.stopforumspam.acplistener:
        class: stopforumspam\stopforumspam\event\acp_listener
        tags:
            - { name: event.listener }

    stopforumspam.stopforumspam.mainlistener:
        class: stopforumspam\stopforumspam\event\main_listener
        arguments:
            - @config
            - @user
            - @log
            - @request
            - @template
            - %core.root_path%
            - %core.php_ext% 
        tags:
            - { name: event.listener }
