services:
     rmcgirr83.stopforumspam.mainlistener:
        class: rmcgirr83\stopforumspam\event\main_listener
        arguments:
            - @config
            - @config_text
            - @user
            - @dbal.conn
            - @log			
            - @request
            - @template
            - %core.root_path%
            - %core.php_ext% 
        tags:
            - { name: event.listener }
